const path = require('path');
require('dotenv').config({ path: path.join('..', '.env') });

module.exports = {
    development: [
        {
            name: 'support',
            username: process.env.DB_USERNAME,
            password: process.env.DB_PASSWORD,
            database: process.env.DB_NAME,
            host: process.env.DB_HOST,
            port: parseInt(process.env.DB_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
            seederStorage: 'sequelize',
            seederStorageTableName: 'SequelizeSeeder',
        },
        {
            name: 'login',
            username: process.env.DB_LOGIN_USERNAME,
            password: process.env.DB_LOGIN_PASSWORD,
            database: process.env.DB_LOGIN_NAME,
            host: process.env.DB_LOGIN_HOST,
            port: parseInt(process.env.DB_LOGIN_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'solution',
            username: process.env.DB_SOLUTION_USERNAME,
            password: process.env.DB_SOLUTION_PASSWORD,
            database: process.env.DB_SOLUTION_NAME,
            host: process.env.DB_SOLUTION_HOST,
            port: parseInt(process.env.DB_SOLUTION_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'label',
            username: process.env.DB_LABEL_USERNAME,
            password: process.env.DB_LABEL_PASSWORD,
            database: process.env.DB_LABEL_NAME,
            host: process.env.DB_LABEL_HOST,
            port: parseInt(process.env.DB_LABEL_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'portal',
            username: process.env.DB_PORTAL_USERNAME,
            password: process.env.DB_PORTAL_PASSWORD,
            database: process.env.DB_PORTAL_NAME,
            host: process.env.DB_PORTAL_HOST,
            port: parseInt(process.env.DB_PORTAL_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'locator',
            username: process.env.DB_LOCATOR_USERNAME,
            password: process.env.DB_LOCATOR_PASSWORD,
            database: process.env.DB_LOCATOR_NAME,
            host: process.env.DB_LOCATOR_HOST,
            port: parseInt(process.env.DB_LOCATOR_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'bloop',
            username: process.env.DB_BLOOP_USERNAME,
            password: process.env.DB_BLOOP_PASSWORD,
            database: process.env.DB_BLOOP_NAME,
            host: process.env.DB_BLOOP_HOST,
            port: parseInt(process.env.DB_BLOOP_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'option',
            username: process.env.DB_OPTION_USERNAME,
            password: process.env.DB_OPTION_PASSWORD,
            database: process.env.DB_OPTION_NAME,
            host: process.env.DB_OPTION_HOST,
            port: parseInt(process.env.DB_OPTION_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'banner',
            username: process.env.DB_BANNER_USERNAME,
            password: process.env.DB_BANNER_PASSWORD,
            database: process.env.DB_BANNER_NAME,
            host: process.env.DB_BANNER_HOST,
            port: parseInt(process.env.DB_BANNER_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
    ],
    production: [
        {
            name: 'support',
            username: process.env.DB_USERNAME,
            password: process.env.DB_PASSWORD,
            database: process.env.DB_NAME,
            host: process.env.DB_HOST,
            port: parseInt(process.env.DB_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
            seederStorage: 'sequelize',
            seederStorageTableName: 'SequelizeSeeder',
        },
        {
            name: 'login',
            username: process.env.DB_LOGIN_USERNAME,
            password: process.env.DB_LOGIN_PASSWORD,
            database: process.env.DB_LOGIN_NAME,
            host: process.env.DB_LOGIN_HOST,
            port: parseInt(process.env.DB_LOGIN_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'solution',
            username: process.env.DB_SOLUTION_USERNAME,
            password: process.env.DB_SOLUTION_PASSWORD,
            database: process.env.DB_SOLUTION_NAME,
            host: process.env.DB_SOLUTION_HOST,
            port: parseInt(process.env.DB_SOLUTION_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'label',
            username: process.env.DB_LABEL_USERNAME,
            password: process.env.DB_LABEL_PASSWORD,
            database: process.env.DB_LABEL_NAME,
            host: process.env.DB_LABEL_HOST,
            port: parseInt(process.env.DB_LABEL_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'portal',
            username: process.env.DB_PORTAL_USERNAME,
            password: process.env.DB_PORTAL_PASSWORD,
            database: process.env.DB_PORTAL_NAME,
            host: process.env.DB_PORTAL_HOST,
            port: parseInt(process.env.DB_PORTAL_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'locator',
            username: process.env.DB_LOCATOR_USERNAME,
            password: process.env.DB_LOCATOR_PASSWORD,
            database: process.env.DB_LOCATOR_NAME,
            host: process.env.DB_LOCATOR_HOST,
            port: parseInt(process.env.DB_LOCATOR_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'bloop',
            username: process.env.DB_BLOOP_USERNAME,
            password: process.env.DB_BLOOP_PASSWORD,
            database: process.env.DB_BLOOP_NAME,
            host: process.env.DB_BLOOP_HOST,
            port: parseInt(process.env.DB_BLOOP_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'option',
            username: process.env.DB_OPTION_USERNAME,
            password: process.env.DB_OPTION_PASSWORD,
            database: process.env.DB_OPTION_NAME,
            host: process.env.DB_OPTION_HOST,
            port: parseInt(process.env.DB_OPTION_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'banner',
            username: process.env.DB_BANNER_USERNAME,
            password: process.env.DB_BANNER_PASSWORD,
            database: process.env.DB_BANNER_NAME,
            host: process.env.DB_BANNER_HOST,
            port: parseInt(process.env.DB_BANNER_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
    ],
    test: [
        {
            name: 'support',
            username: process.env.DB_USERNAME,
            password: process.env.DB_PASSWORD,
            database: process.env.DB_NAME,
            host: process.env.DB_HOST,
            port: parseInt(process.env.DB_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
            seederStorage: 'sequelize',
            seederStorageTableName: 'SequelizeSeeder',
        },
        {
            name: 'login',
            username: process.env.DB_LOGIN_USERNAME,
            password: process.env.DB_LOGIN_PASSWORD,
            database: process.env.DB_LOGIN_NAME,
            host: process.env.DB_LOGIN_HOST,
            port: parseInt(process.env.DB_LOGIN_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'solution',
            username: process.env.DB_SOLUTION_USERNAME,
            password: process.env.DB_SOLUTION_PASSWORD,
            database: process.env.DB_SOLUTION_NAME,
            host: process.env.DB_SOLUTION_HOST,
            port: parseInt(process.env.DB_SOLUTION_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'label',
            username: process.env.DB_LABEL_USERNAME,
            password: process.env.DB_LABEL_PASSWORD,
            database: process.env.DB_LABEL_NAME,
            host: process.env.DB_LABEL_HOST,
            port: parseInt(process.env.DB_LABEL_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'portal',
            username: process.env.DB_PORTAL_USERNAME,
            password: process.env.DB_PORTAL_PASSWORD,
            database: process.env.DB_PORTAL_NAME,
            host: process.env.DB_PORTAL_HOST,
            port: parseInt(process.env.DB_PORTAL_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'locator',
            username: process.env.DB_LOCATOR_USERNAME,
            password: process.env.DB_LOCATOR_PASSWORD,
            database: process.env.DB_LOCATOR_NAME,
            host: process.env.DB_LOCATOR_HOST,
            port: parseInt(process.env.DB_LOCATOR_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'bloop',
            username: process.env.DB_BLOOP_USERNAME,
            password: process.env.DB_BLOOP_PASSWORD,
            database: process.env.DB_BLOOP_NAME,
            host: process.env.DB_BLOOP_HOST,
            port: parseInt(process.env.DB_BLOOP_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'option',
            username: process.env.DB_OPTION_USERNAME,
            password: process.env.DB_OPTION_PASSWORD,
            database: process.env.DB_OPTION_NAME,
            host: process.env.DB_OPTION_HOST,
            port: parseInt(process.env.DB_OPTION_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
        {
            name: 'banner',
            username: process.env.DB_BANNER_USERNAME,
            password: process.env.DB_BANNER_PASSWORD,
            database: process.env.DB_BANNER_NAME,
            host: process.env.DB_BANNER_HOST,
            port: parseInt(process.env.DB_BANNER_PORT || '3306'),
            dialect: 'mysql',
            logging: false,
        },
    ],
};
